### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by jbpin** [AlteredConstants/odata-batch-request#4]
Hi, thanks for your lib, how can I set a global bearer token on the request ?

**Comment by AlteredConstants** [comment]
This library doesn't actually make the request itself. It constructs the various pieces of it for you (and also can parse the response), but you need to make the request yourself in whatever way is appropriate for your context.

There are two places you can add headers to, for instance, include a bearer token: either in the individual operations themselves or in the actual network request. For example:

```ts
const batch = new ODataBatchRequest("/api", [
  new ODataBatchOperation("get", "users", {
    headers: {
      // I don't suspect this is what you want but you can add any
      // headers you might need for a specific operation here.
      Authorization: `Bearer ${token}`,
    },
  }),
])

// Make the actual request with whatever mechanism your project uses.
const response = await fetch(batch.url, {
  method: "POST",
  body: batch.body,
  headers: {
    ...batch.headers,
    // This is probably where you actually need it.
    Authorization: `Bearer ${token}`,
  },
})
```

Hope that helps!
